version: "3.7"

services:

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redisData:/data
    networks:
      - servicesNetwork

  rabbitmq:
    image: 'rabbitmq:3.7-alpine'
    container_name: events_rabbit
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    networks:
      - servicesNetwork
    volumes:
      - 'rabbitmqData:/bitnami'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=events

  # ------ USERS SERVICE
  users_webserver:
    image: nginx:alpine
    container_name: 'users_webserver'
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/users/sites:/etc/nginx/conf.d
      - ./docker/nginx/users/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./services/users:/var/www/html
    networks:
      - servicesNetwork

  users_php:
    build: docker/php
    container_name: 'users_php'
    volumes:
      - ./services/users:/var/www/html
    networks:
      - servicesNetwork

  users_db:
    image: mysql:5.7
    container_name: users_db
    ports:
      - "33060:3306"
    volumes:
      - usersDbData:/var/lib/mysql
    networks:
      - servicesNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: users
      MYSQL_PASSWORD: secret


  # ------ ACL SERVICE
  acl_webserver:
    image: nginx:alpine
    container_name: 'acl_webserver'
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx/acl/sites:/etc/nginx/conf.d
      - ./docker/nginx/acl/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./services/acl:/var/www/html
    networks:
      - servicesNetwork

  acl_php:
    build: docker/php
    container_name: 'acl_php'
    volumes:
      - ./services/acl:/var/www/html
    networks:
      - servicesNetwork

  acl_db:
    image: mysql:5.7
    container_name: acl_db
    ports:
      - "33061:3306"
    volumes:
      - aclDbData:/var/lib/mysql
    networks:
      - servicesNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acl
      MYSQL_USER: acl
      MYSQL_PASSWORD: secret


networks:
  servicesNetwork:
    driver: "bridge"


volumes:
  redisData:
    driver: "local"
  rabbitmqData:
    driver: "local"
  usersDbData:
    driver: "local"
  aclDbData:
    driver: "local"
